export const USER_SIGNIN = 'USER_SIGNIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const SAVE_PAYSLIP = 'SAVE_PAYSLIP';
export const GET_EMPLOYEE_PAY_HISTORY = 'GET_EMPLOYEE_PAY_HISTORY';
export const USER_SIGNUP = 'USER_SIGNUP';
