export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_USER_LOGIN_ERROR = 'SET_USER_LOGIN_ERROR';
export const SET_EMPLOYEE_INFO = 'SET_EMPLOYEE_INFO';
export const REMOVE_EMPLOYEE_INFO = 'REMOVE_EMPLOYEE_INFO';
